#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.
#

prev_one = 1
prev_two = 2

fib = prev_one + prev_two
total_sum = 2

while (fib < 4000000)
  total_sum += fib if (fib % 2 == 0)
  prev_one = prev_two
  prev_two = fib
  fib = prev_one + prev_two
end

puts total_sum

# time ruby two.rb
#
# real  0m0.013s
# user  0m0.006s
# sys   0m0.005s
